name: Deploy Angular to Github Pages

on:
  push:
    branches:
      - release

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: Build Angular
    runs-on: ubuntu-latest
  
    steps:

      - name: Checkout repository
        uses: actions/checkout@v6
      
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: npm
      
      - name: Install dependecies
        run: npm ci
      
      - name: Build Angular
        run: npm run build -- --base-href /frontend_proyecto/
      
      - name: Upload Github Pages artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: dist/frontend_proyecto/browser
  
  deploy:
    name: Deploy to Github Pages
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    
    steps:

      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v4
